export const hyperblogsCopy = {
  title: "Hyperblog Library",
  description:
    "View and create Hyperblogs from the {graphLabel} Bonfire. Content is generated by AI, informed by the graph and paid for using x402 payments on Base.",
  dataroomTitle: "Topics",
  dataroomDescription: "Topics provide a specific focus and theme for Hyperblog creators to choose from. You may view existing Hyperblogs generated in each Topic, or create your own.",
  dataroomTooltipContent: ["A Topic represents a designated \"focus\" node on the Bonfire graph that pertains to a chosen subject area.",  "Clicking \"Explore Graph\" will take you to the Explorer with the Topic node as its center.",  "If you wish to create a new Topic, contact a Bonfires team member."],
  createTitle: "Create Blog",
  createDescription: "Generate an AI-powered blog post from this dataroom's knowledge graph",
  createTooltipContent: "Describe what you want the content to be about; mention specific topics, themes or subjects if you wish to see them in the blog.",
  createDescriptionPlaceholder: "Describe what you want the blog to cover (Max 600 characters)",
};
